[data]
git-tree-sha1 = "ea201d8bf1db766e37d2bfdc2c33412b85e23e51"

    [[data.download]]
    url = "https://github.com/MindTheGap-ERC/CarboKittenData/archive/refs/tags/v1.1.tar.gz"
    sha256 = "12cfac07ebbe89ffc61a5f6e46b25f68d6ba4fc5606d6636bf6eae3f91b4b63a"