version="2.0"
watch_list=["docs/src/*.md"]
hooks=["build"]

[hook.build.runners]
# Daemon should be running:
#   julia --startup-file=no -e 'using DaemonMode; serve()'
Julia = "julia --project=. --startup-file=no -e 'using DaemonMode; runargs()' {script}"
Gnuplot = "gnuplot {script} > $@"

